### ISSUE TITLE
Is this the algorithm I seek?

### ISSUE THREAD

**Issue by jpstrikesback** [lyft/coloralgorithm#4] opened 2018-09-24 19:04 UTC
Is this what was rumoured about at:

https://design.lyft.com/re-approaching-color-9e604ba22c88

and which powers:

https://www.colorbox.io/

Is it?

**Comment by rtpHarry** [comment] 2018-09-30 06:31
According to this yes:

https://wptavern.com/lyft-open-sources-colorbox-algorithm-for-building-accessible-color-systems

(that's how I got here... the readme is pretty vague)

**Comment by soffes** [comment] 2018-11-26 17:05
It is! Closing this as a duplicate of #7 since it's more specific about the ask :)

**Closed by soffes** 2018-11-26 17:05 UTC
